### ISSUE TITLE
有可能实现日语歌词的注音/翻译切换显示吗

### ISSUE THREAD

**Issue by lychichem** [Robotxm/ESLyric-LyricsSource#1]
现在的酷狗用户，曾经也用foobox，用酷狗还是看上了逐字显示和日语歌词注音这两样。效果大概这样：
注音显示：
![image](https://user-images.githubusercontent.com/9316590/51074004-11332680-16b4-11e9-9e09-c18eda6da25f.png)
我因为不了解krc的数据格式，也没有强大到能直接打开krc的文本编辑器，不是很清楚注音数据的存储位置，所以想问下前辈有没有肯能实现这个效果，当然没有也无妨，现在的已经很好了

**Comment by Robotxm** [comment]
首先非常感谢你能发现并关注我这个小玩意。
关于你说的音译歌词，之前有思考过。不过因为 ESLyric 本身的限制，不能像酷狗那样和日语歌词同步滚动并高亮。如果要加的话只能像是翻译歌词一样，直接显示在原始歌词的下面。如图：
![default](https://user-images.githubusercontent.com/5405331/51074349-1d6db280-16b9-11e9-8b94-2674df85c8b8.png)
上面原始的日文歌词可以按照时间轴实现卡拉 OK 效果，而下面的仅仅是放在那里显示而已。

**Comment by lychichem** [comment]
@Robotxm 果然想投机取巧唱罗马音看来是不行呢（笑），看来只能暂时要么用酷狗并忍受每次都提示我装flash，要么努力学日语了。改eslyric感觉难度太大而且还会影响本来的双排歌词显示也不太好（除非做成开关），总之会是个大工程的样子

**Comment by Robotxm** [comment]
嘛，其实目前能将就实现的音译歌词难度不大，照抄翻译歌词的代码就行了。不过效果上因为没有卡拉 OK 的逐字滚动，加上切换音译和翻译需要改 js 中的变量（就像目前的 Alpha 和 Beta 功能一样）然后重新写入到 ESLyric 能识别的格式里，所以和翻译歌词共存几乎是不可能的，我就一直没管；还有个原因就是本来是自用（传 GayHub 只是备份代码）就没加（笑）

**Comment by ghost** [comment]
ESlyric 作者在做个简单的歌词插件，有显示双语的功能。不过鸽掉的可能性不小...

**Comment by Robotxm** [comment]
@elia-is-me 但愿他别鸽，这样就不用这么费劲整脚本了。我这种处理歌词的方法其实蛮难受的，如果改个我这脚本里的设置还得重新处理一遍歌词。
