### ISSUE TITLE
网易云ex源双语歌词对应出现问题

### ISSUE THREAD

**Issue by renceing** [Robotxm/ESLyric-LyricsSource#11]
您好，我在使用网易云ex源时，每一行的日文歌词会对应到下句的中文歌词，即上一段下半部分的中文和下一段日文的歌词才是完整的一句双语歌词，劳烦进行修复Q！
![image](https://github.com/Robotxm/ESLyric-LyricsSource/assets/139771913/9a6b4db9-9b19-4570-b4e5-1445ae9c34c2)
如果使用的是这张图片上方的“网易云”源（来源于作者ohyeah），歌词正确地显示成这样
![image](https://github.com/Robotxm/ESLyric-LyricsSource/assets/139771913/7eba09fb-b69f-46ee-943a-580147f4565c)
但在使用下方您的“网易云ex”源时，歌词会显示成这样
![image](https://github.com/Robotxm/ESLyric-LyricsSource/assets/139771913/f589d2ca-70e1-415a-9ea5-9265e20e99fc)

eslyric版本号：v0.5.4.1028 (Beta)
歌词源是最新版本

**Comment by Robotxm** [comment]
已修复。

**Comment by renceing** [comment]
@Robotxm 真的非常感谢！
