### ISSUE TITLE
新版ESLyric无法使用QQ音乐Ex脚本

### ISSUE THREAD

**Issue by FQDianYan** [Robotxm/ESLyric-LyricsSource#12]
QQ音乐Ex脚本配合ESLyric 1.0.0.1016 Alpha 无法显示歌词搜索结果，将ESLyric降级到0.5.4.1028之后可以显示歌词搜索结果。
  请升级QQ音乐Ex脚本兼容新版本ESLyric，谢谢。

**Comment by Robotxm** [comment]
已修复。
