### ISSUE TITLE
是否可能将歌词排版增加并排显示选项（即翻译显示在同一行）

### ISSUE THREAD

**Issue by humuhan** [Robotxm/ESLyric-LyricsSource#3]
你好，插件很好用，有个请求，是否可能增加歌词并排显示的选项？
可能有些人像我一样并不使用eslyric的桌面歌词功能只在foobar内面板看歌词，希望可以不要上下行显示。
我完全不懂代码，有个作者的网易云歌词获取做得很好，搜索歌词的时候有“并排”或者“并列”可选
https://github.com/EHfive/Some-js-script-for-FB2K/blob/master/ncm.js
界面如图
![image](https://user-images.githubusercontent.com/11542979/71323485-b7b3b880-250e-11ea-8c15-4127bbcf1246.png)

**Comment by Robotxm** [comment]
考虑到 ESLyric 的歌词处理机制和解析器的通用性，目前没有为酷狗歌词增加并排显示的计划。
