### ISSUE TITLE
QQ音乐逐字歌词显示问题

### ISSUE THREAD

**Issue by MC-dusk** [Robotxm/ESLyric-LyricsSource#6]
您好，脚本很好用，但是来自QQ音乐的逐字歌词（不知道这个脚本获取的是不是逐字版本的歌词），经过脚本处理，已经变成逐行的歌词，ESLyric是支持逐字歌词的，不太懂js，没看代码，不知道这个问题容不容易解决。
有人做过qrc解码转ESLyric可用的逐字歌词：https://github.com/qwe7989199/Lyric-Importer-for-Aegisub
https://gitee.com/ying32/MakeLyric

**Comment by Robotxm** [comment]
感谢反馈。脚本获取的是 QQ 音乐的逐行歌词，之前因为没有解密算法，并且我本人对逆向方面不是特别了解，所以只能做到这个程度。回头我抽空研究一下你提供的链接，看看 QRC 逐字能不能做到。

**Comment by dtjiangchi** [comment]
作者你好，很感谢你做这个插件，目前播放日语歌的时候，歌词时间轴有的歌曲会有误，日语里的汉字的片甲注释在同行显示

**Comment by Robotxm** [comment]
> 作者你好，很感谢你做这个插件，目前播放日语歌的时候，歌词时间轴有的歌曲会有误，日语里的汉字的片甲注释在同行显示

ESLyric 不支持像 QQ 音乐一样的假名显示方式

**Comment by MC-dusk** [comment]
在这里贴一下吧，如果有人想使用QQ音乐精准逐字的歌词，可以用[这个](https://github.com/MC-dusk/QRCD_M)下载歌词，用foobar2000打开就行了

**Comment by Robotxm** [comment]
已添加 QRC 逐字歌词及翻译支持，需配合最新版 ESLyric 使用

**Comment by MC-dusk** [comment]
> 已添加 QRC 逐字歌词及翻译支持，需配合最新版 ESLyric 使用

没有qrc的searcher文件夹，只给了parser

**Comment by MC-dusk** [comment]
> > 已添加 QRC 逐字歌词及翻译支持，需配合最新版 ESLyric 使用
> 
> 没有qrc的searcher文件夹，只给了parser

感谢修复，请问能给个测试例吗，我没找到一首QQ音乐源，逐字歌词，并且有翻译的歌...

**Comment by Robotxm** [comment]
> > > 已添加 QRC 逐字歌词及翻译支持，需配合最新版 ESLyric 使用
> > 
> > 
> > 没有qrc的searcher文件夹，只给了parser
> 
> 感谢修复，请问能给个测试例吗，我没找到一首QQ音乐源，逐字歌词，并且有翻译的歌...

QQ 音乐的翻译歌词经常会出现和原始歌词行数不对应的情况，暂时不清楚官方客户端是怎么处理这个情况的。这种情况下脚本只会返回原始歌词。后面我再看看有没有什么办法来解决这个吧。

可以试一下 wacci 的あなたがいる这首歌。

**Comment by MC-dusk** [comment]
测试结果：https://gist.github.com/MC-dusk/fef261f49f92fbe9df34f619d1b6b492
