### ISSUE TITLE
新版krc解析后，翻译歌词不能复制或编辑

### ISSUE THREAD

**Issue by MC-dusk** [Robotxm/ESLyric-LyricsSource#8]
下载安装了https://github.com/ESLyric/release ，再覆盖更新了krc.js，酷狗音乐源解析后，panel能看到双语歌词，但copy后的歌词没有翻译，内置编辑器edit也没有翻译歌词。
foobar2000 v2.0 beta 17 64bit
eslyric [0.5.3.1019](https://github.com/ESLyric/release/releases/tag/0.5.3.1019)

**Comment by Robotxm** [comment]
这些属于 ESLyric 插件问题，**请向插件作者反馈，与脚本无关**。

1. 请使用面板右键菜单的“复制歌词”→“复制...”来选择要复制什么内容
2. 按照 ESLyric 作者[说法](https://github.com/ESLyric/feedback/issues/19)，不支持在内置编辑器中编辑带有参考行的歌词

**Comment by MC-dusk** [comment]
抱歉，因为我看网易云音乐的源的双语歌词是正常的，就没想到是eslyric的问题。逐行逐字模式有区别，后续我会去反馈。
