### ISSUE TITLE
QQ Music Ex 不显示标题

### ISSUE THREAD

**Issue by david4958606** [Robotxm/ESLyric-LyricsSource#9]
<img width="409" alt="image" src="https://github.com/Robotxm/ESLyric-LyricsSource/assets/16517322/025d5222-d359-46fa-8b0a-27b6e28ebbf4">

如图，可以获取到歌词内容，但在搜索界面看不到标题

**Comment by Robotxm** [comment]
这个问题应该是 QQ 音乐的问题，我用官方客户端尝试搜索歌词，也没办法展示标题
